from . import regex

PROPERTY_LIST = [
    "object-length",
    "source-loop",
    "playback-speed",
    "time-margin",
    "time-margin-start",
    "time-margin-end",
    "time-padding",
    "time-padding-start",
    "time-padding-end",
    "order",
    "layer-mode",
    "opacity",
    "width",
    "min-width",
    "max-width",
    "height",
    "min-height",
    "max-height",
    "background-color",
    "object-fit",
    "chroma-key",
    "magnification",
    "rotate",
    "border",
    "border-color",
    "border-style",
    "border-width",
    "border-bottom",
    "border-bottom-color",
    "border-bottom-style",
    "border-bottom-width",
    "border-left",
    "border-left-color",
    "border-left-style",
    "border-left-width",
    "border-right",
    "border-right-color",
    "border-right-style",
    "border-right-width",
    "border-top",
    "border-top-color",
    "border-top-style",
    "border-top-width",
    "position",
    "display",
    "top",
    "left",
    "bottom",
    "right",
    "flex-direction",
    "flex-wrap",
    "align-content",
    "justify-content",
    "align-items",
    "margin",
    "margin-top",
    "margin-left",
    "margin-bottom",
    "margin-right",
    "padding",
    "padding-top",
    "padding-left",
    "padding-bottom",
    "padding-right",
    "border-radius",
    "border-bottom-left-radius",
    "border-bottom-right-radius",
    "border-top-left-radius",
    "border-top-right-radius",
    "visibility",
    "box-shadow",
    "audio-volume",
    "audio-system",
    "font-color",
    "font-border",
    "font-border-color",
    "font-border-width",
    "font",
    "font-family",
    "font-size",
    "font-stretch",
    "font-style",
    "font-weight",
    "text-align",
    "text-decoration",
    "text-decoration-color",
    "text-decoration-line",
    "text-decoration-style",
    "text-decoration-thickness",
    "text-orientation",
    "text-overflow",
    "text-shadow",
    "line-height",
    "letter-spacing",
    "word-break",
]

COLOR_LIST = [
    "aliceblue",
    "antiquewhite",
    "aqua",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgreen",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dodgerblue",
    "firebrick",
    "floralwhite",
    "forestgreen",
    "fuchsia",
    "gainsboro",
    "ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "green",
    "greenyellow",
    "honeydew",
    "hotpink",
    "indianred",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgreen",
    "lightgrey",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightslategray",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navajowhite",
    "navy",
    "oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    "seashell",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "slategray",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    "white",
    "whitesmoke",
    "yellow",
    "yellowgreen",
]

COLOR_VALUE = {
    "aliceblue": [240, 248, 255],
    "antiquewhite": [250, 235, 215],
    "aqua": [0, 255, 255],
    "aquamarine": [127, 255, 212],
    "azure": [240, 255, 255],
    "beige": [245, 245, 220],
    "bisque": [255, 228, 196],
    "black": [0, 0, 0],
    "blanchedalmond": [255, 235, 205],
    "blue": [0, 0, 255],
    "blueviolet": [138, 43, 226],
    "brown": [165, 42, 42],
    "burlywood": [222, 184, 135],
    "cadetblue": [95, 158, 160],
    "chartreuse": [127, 255, 0],
    "chocolate": [210, 105, 30],
    "coral": [255, 127, 80],
    "cornflowerblue": [100, 149, 237],
    "cornsilk": [255, 248, 220],
    "crimson": [220, 20, 60],
    "cyan": [0, 255, 255],
    "darkblue": [0, 0, 139],
    "darkcyan": [0, 139, 139],
    "darkgoldenrod": [184, 134, 11],
    "darkgray": [169, 169, 169],
    "darkgreen": [0, 100, 0],
    "darkkhaki": [189, 183, 107],
    "darkmagenta": [139, 0, 139],
    "darkolivegreen": [85, 107, 47],
    "darkorange": [255, 140, 0],
    "darkorchid": [153, 50, 204],
    "darkred": [139, 0, 0],
    "darksalmon": [233, 150, 122],
    "darkseagreen": [143, 188, 143],
    "darkslateblue": [72, 61, 139],
    "darkslategray": [47, 79, 79],
    "darkturquoise": [0, 206, 209],
    "darkviolet": [148, 0, 211],
    "deeppink": [255, 20, 147],
    "deepskyblue": [0, 191, 255],
    "dimgray": [105, 105, 105],
    "dodgerblue": [30, 144, 255],
    "firebrick": [178, 34, 34],
    "floralwhite": [255, 250, 240],
    "forestgreen": [34, 139, 34],
    "fuchsia": [255, 0, 255],
    "gainsboro": [220, 220, 220],
    "ghostwhite": [248, 248, 255],
    "gold": [255, 215, 0],
    "goldenrod": [218, 165, 32],
    "gray": [128, 128, 128],
    "green": [0, 128, 0],
    "greenyellow": [173, 255, 47],
    "honeydew": [240, 255, 240],
    "hotpink": [255, 105, 180],
    "indianred": [205, 92, 92],
    "indigo": [75, 0, 130],
    "ivory": [255, 255, 240],
    "khaki": [240, 230, 140],
    "lavender": [230, 230, 250],
    "lavenderblush": [255, 240, 245],
    "lawngreen": [124, 252, 0],
    "lemonchiffon": [255, 250, 205],
    "lightblue": [173, 216, 230],
    "lightcoral": [240, 128, 128],
    "lightcyan": [224, 255, 255],
    "lightgoldenrodyellow": [250, 250, 210],
    "lightgreen": [144, 238, 144],
    "lightgrey": [211, 211, 211],
    "lightpink": [255, 182, 193],
    "lightsalmon": [255, 160, 122],
    "lightseagreen": [32, 178, 170],
    "lightskyblue": [135, 206, 250],
    "lightslategray": [119, 136, 153],
    "lightsteelblue": [176, 196, 222],
    "lightyellow": [255, 255, 224],
    "lime": [0, 255, 0],
    "limegreen": [50, 205, 50],
    "linen": [250, 240, 230],
    "magenta": [255, 0, 255],
    "maroon": [128, 0, 0],
    "mediumaquamarine": [102, 205, 170],
    "mediumblue": [0, 0, 205],
    "mediumorchid": [186, 85, 211],
    "mediumpurple": [147, 112, 216],
    "mediumseagreen": [60, 179, 113],
    "mediumslateblue": [123, 104, 238],
    "mediumspringgreen": [0, 250, 154],
    "mediumturquoise": [72, 209, 204],
    "mediumvioletred": [199, 21, 133],
    "midnightblue": [25, 25, 112],
    "mintcream": [245, 255, 250],
    "mistyrose": [255, 228, 225],
    "moccasin": [255, 228, 181],
    "navajowhite": [255, 222, 173],
    "navy": [0, 0, 128],
    "oldlace": [253, 245, 230],
    "olive": [128, 128, 0],
    "olivedrab": [107, 142, 35],
    "orange": [255, 165, 0],
    "orangered": [255, 69, 0],
    "orchid": [218, 112, 214],
    "palegoldenrod": [238, 232, 170],
    "palegreen": [152, 251, 152],
    "paleturquoise": [175, 238, 238],
    "palevioletred": [216, 112, 147],
    "papayawhip": [255, 239, 213],
    "peachpuff": [255, 218, 185],
    "peru": [205, 133, 63],
    "pink": [255, 192, 203],
    "plum": [221, 160, 221],
    "powderblue": [176, 224, 230],
    "purple": [128, 0, 128],
    "red": [255, 0, 0],
    "rosybrown": [188, 143, 143],
    "royalblue": [65, 105, 225],
    "saddlebrown": [139, 69, 19],
    "salmon": [250, 128, 114],
    "sandybrown": [244, 164, 96],
    "seagreen": [46, 139, 87],
    "seashell": [255, 245, 238],
    "sienna": [160, 82, 45],
    "silver": [192, 192, 192],
    "skyblue": [135, 206, 235],
    "slateblue": [106, 90, 205],
    "slategray": [112, 128, 144],
    "snow": [255, 250, 250],
    "springgreen": [0, 255, 127],
    "steelblue": [70, 130, 180],
    "tan": [210, 180, 140],
    "teal": [0, 128, 128],
    "thistle": [216, 191, 216],
    "tomato": [255, 99, 71],
    "turquoise": [64, 224, 208],
    "violet": [238, 130, 238],
    "wheat": [245, 222, 179],
    "white": [255, 255, 255],
    "whitesmoke": [245, 245, 245],
    "yellow": [255, 255, 0],
    "yellowgreen": [154, 205, 50],
}


SECOND_PATTERN = "{}s".format(regex.REAL_NUMBER_PATTERN)
FRAME_PATTERN = "{}f".format(regex.REAL_NUMBER_PATTERN)

PIXEL_PATTERN = "{}px".format(regex.REAL_NUMBER_PATTERN)
RESOLUTION_WIDTH_PATTERN = "{}rw".format(regex.REAL_NUMBER_PATTERN)
RESOLUTION_HEIGHT_PATTERN = "{}rh".format(regex.REAL_NUMBER_PATTERN)
RESOLUTION_MIN_PATTERN = "{}rmin".format(regex.REAL_NUMBER_PATTERN)
RESOLUTION_MAX_PATTERN = "{}rmax".format(regex.REAL_NUMBER_PATTERN)

PERCENT_PATTERN = "{}%".format(regex.REAL_NUMBER_PATTERN)

TIME_PATTERN = "({}|{}|{}|0)".format(
    SECOND_PATTERN, FRAME_PATTERN, PERCENT_PATTERN
)
GRAPHIC_PATTERN = "({}|{}|{}|{}|{}|{}|0)".format(
    PIXEL_PATTERN,
    RESOLUTION_WIDTH_PATTERN,
    RESOLUTION_HEIGHT_PATTERN,
    RESOLUTION_MIN_PATTERN,
    RESOLUTION_MAX_PATTERN,
    PERCENT_PATTERN,
)

HEX_COLOR_PATTERN = "#({0}{{3}}|{0}{{4}}|{0}{{6}}|{0}{{8}})".format(
    regex.HEX_PATTERN
)
RGB_COLOR_PATTERN = r"rgb\(\s*{0}\s*,\s*{0}\s*,\s*{0}\s*\)".format(
    regex.REAL_NUMBER_PATTERN
)
RGBA_COLOR_PATTERN = r"rgba\(\s*{0}\s*,\s*{0}\s*,\s*{0}\s*,\s*{0}\s*\)".format(
    regex.REAL_NUMBER_PATTERN
)
PURE_COLOR_PATTERN = "|".join(COLOR_LIST)
COLOR_PATTERN = "({}|{}|{}|{})".format(
    PURE_COLOR_PATTERN,
    HEX_COLOR_PATTERN,
    RGB_COLOR_PATTERN,
    RGBA_COLOR_PATTERN,
)

STYLE_VALUE_PATTERN = {
    "object-length": "(fit|source|{})".format(TIME_PATTERN),
    "source-loop": "(true|false)",
    "playback-speed": PERCENT_PATTERN,
    "time-margin": r"{0}(\s+{0})?".format(TIME_PATTERN),
    "time-margin-start": TIME_PATTERN,
    "time-margin-end": TIME_PATTERN,
    "time-padding": r"{0}(\s+{0})?".format(TIME_PATTERN),
    "time-padding-start": TIME_PATTERN,
    "time-padding-end": TIME_PATTERN,
    "order": "(sequence|parallel)",
    "layer-mode": "(single|multi)",
    "opacity": "({}|{})".format(regex.REAL_NUMBER_PATTERN, PERCENT_PATTERN),
    "width": GRAPHIC_PATTERN,
    "min-width": "",
    "max-width": "",
    "height": GRAPHIC_PATTERN,
    "min-height": "",
    "max-height": "",
    "background-color": COLOR_PATTERN,
    "object-fit": "",
    "chroma-key": "",
    "magnification": "",
    "rotate": "",
    "border": "",
    "border-color": "",
    "border-style": "",
    "border-width": "",
    "border-bottom": "",
    "border-bottom-color": "",
    "border-bottom-style": "",
    "border-bottom-width": "",
    "border-left": "",
    "border-left-color": "",
    "border-left-style": "",
    "border-left-width": "",
    "border-right": "",
    "border-right-color": "",
    "border-right-style": "",
    "border-right-width": "",
    "border-top": "",
    "border-top-color": "",
    "border-top-style": "",
    "border-top-width": "",
    "position": "",
    "display": "",
    "top": "",
    "left": "",
    "bottom": "",
    "right": "",
    "flex-direction": "",
    "flex-wrap": "",
    "align-content": "",
    "justify-content": "",
    "align-items": "",
    "margin": r"{0}(\s+{0}){1}".format(GRAPHIC_PATTERN, "{0,3}"),
    "margin-top": GRAPHIC_PATTERN,
    "margin-left": GRAPHIC_PATTERN,
    "margin-bottom": GRAPHIC_PATTERN,
    "margin-right": GRAPHIC_PATTERN,
    "padding": r"{0}(\s+{0}){1}".format(GRAPHIC_PATTERN, "{0,3}"),
    "padding-top": GRAPHIC_PATTERN,
    "padding-left": GRAPHIC_PATTERN,
    "padding-bottom": GRAPHIC_PATTERN,
    "padding-right": GRAPHIC_PATTERN,
    "border-radius": "",
    "border-bottom-left-radius": "",
    "border-bottom-right-radius": "",
    "border-top-left-radius": "",
    "border-top-right-radius": "",
    "visibility": "",
    "box-shadow": "",
    "audio-volume": PERCENT_PATTERN,
    "audio-system": "(monaural|stereo)",
    "font-color": COLOR_PATTERN,
    "font-border": r"({0}\s+{1}|{1}\s+{0})".format(
        COLOR_PATTERN, PIXEL_PATTERN
    ),
    "font-border-color": COLOR_PATTERN,
    "font-border-width": PIXEL_PATTERN,
    "font": "",
    "font-family": ".+",
    "font-size": GRAPHIC_PATTERN,
    "font-stretch": "",
    "font-style": "(normal|italic)",
    "font-weight": "(normal|bold)",
    "text-align": "",
    "text-decoration": "",
    "text-decoration-color": "",
    "text-decoration-line": "",
    "text-decoration-style": "",
    "text-decoration-thickness": "",
    "text-orientation": "",
    "text-overflow": "",
    "text-shadow": "",
    "line-height": "",
    "letter-spacing": "",
    "word-break": "",
}
